<a href="https://colab.research.google.com/github/marisbotero/ML/blob/master/Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [0]:

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[6,5],[4,3],[2,1]])
print(a+b)

[[7 7]
 [7 7]
 [7 7]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [0]:

m=np.array([[6,3],[9,5],[4,8]])
n=2.5
print(m+n)

[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [0]:

j=np.array([[9,2,3],[3,7,4],[5,6,9]])
jt=j.T
print(jt)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [0]:

(jt.T)

array([[9, 2, 3],
       [3, 7, 4],
       [5, 6, 9]])

# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [0]:
A = np.array([[1,2],[0,2]])
d = np.array([[1,0],[1,0]])


C = A * d


In [0]:
C

array([[1, 0],
       [0, 0]])

# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [0]:
L=np.array([[3,5],[7,1]])
K=np.array([[3,12],[6,4]])
respuesta =(L.dot(K))

In [0]:
respuesta

array([[39, 56],
       [27, 88]])

# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5

In [0]:
D = np.array([[1,2,0],[1,2,0], [0,1,1] ])

dte= np.linalg.det(D)
dte

0.0

# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1

In [0]:
F = np.array([[0,1,1],[1,0,0], [0,0,1] ])

det2 = np.linalg.det(F)

det2

-1.0

# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
16 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [0]:
m_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m_2 = np.array([0,2,0])


resu= m_1 * m_2
resu

array([[ 0,  4,  0],
       [ 0, 10,  0],
       [ 0, 16,  0]])