In [0]:
!pip3 install torch torchvision

In [0]:
import torch
num_entries = 5000
db = torch.rand(num_entries)>0.5

In [0]:
db

tensor([1, 1, 0,  ..., 0, 0, 1], dtype=torch.uint8)

#  Build a private database with python
### Create a database
###  create all parallel databases

In [0]:
db = torch.rand(num_entries)>0.5
db

tensor([0, 1, 1,  ..., 0, 0, 1], dtype=torch.uint8)

In [0]:
db.shape

torch.Size([5000])

In [0]:
db[0:5]

tensor([0, 1, 1, 0, 1], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
#db[:3]

In [0]:
def get_parallel_db(db, remove_index):
  
  return torch.cat((db[0:remove_index], db[3: remove_index + 1 ]))

In [0]:
get_parallel_db(db,2)[0:5]

tensor([0, 1], dtype=torch.uint8)

In [0]:
get_parallel_db(db,58934).shape

torch.Size([9997])

In [0]:
def get_parallels_dbs(db):
  parallels_dbs= list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db,i)
    parallels_dbs.append(pdb)
  return paralles_dbs

In [0]:
#len(parallels_dbs)

In [0]:
#get_parallels_dbs(db)