<a href="https://colab.research.google.com/github/marisbotero/ML/blob/master/Differencial_privacity_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch torchvision

In [0]:
import torch
num_entries = 5000
db = torch.rand(num_entries)>0.5

In [3]:
db

tensor([0, 1, 0,  ..., 0, 0, 1], dtype=torch.uint8)

#  Build a private database with python
### Create a database
###  create all parallel databases

In [4]:
db = torch.rand(num_entries)>0.5
db

tensor([0, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [5]:
db.shape

torch.Size([5000])

In [6]:
db[0:5]

tensor([0, 1, 0, 0, 0], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
#db[:3]

In [0]:
def get_parallel_db(db, remove_index):
  
  return torch.cat((db[0:remove_index], db[3: remove_index + 1 ]))

In [9]:
get_parallel_db(db,2)[0:5]

tensor([0, 1], dtype=torch.uint8)

In [10]:
get_parallel_db(db,58934).shape

torch.Size([9997])

In [0]:
def get_parallels_dbs(db):
  parallels_dbs= list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db,i)
    parallels_dbs.append(pdb)
  return paralles_dbs

In [0]:
#len(parallels_dbs)

In [0]:
#get_parallels_dbs(db)

In [11]:
db = torch.rand(num_entries)>0.5
db

tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8)

In [12]:
db.shape

torch.Size([5000])

In [14]:
db[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [0]:
remove_index = 2

In [15]:
db[0:2]

tensor([0, 0], dtype=torch.uint8)

In [16]:
db[3:]

tensor([1, 1, 1,  ..., 0, 0, 1], dtype=torch.uint8)

In [0]:
#torch.cat((db[0:2], db[0:3]))[0:5]
def get_parallel_db(db, remove_index):
  return torch.cat((db[0:remove_index], db[remove_index+1:]))
  
  

In [21]:
get_parallel_db(db,3)[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb= get_parallel_db(db,i)
    parallel_dbs.append(pdb)
  return parallel_dbs

In [24]:
len(parallel_dbs)

5000

In [0]:
pdbs = get_parallel_dbs(db)

In [27]:
pdbs

[tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 0